language: rust

rust:
#  - 1.10.0
#  - stable
  - beta
  - nightly
  
matrix:
  allow_failures:
    - rust: nightly
    
script:
  - cargo build --verbose
  - cargo test --verbose -p rust_lsp -p melnorme_util -p melnorme_jsonrpc
  - cd subcrates/DummyLSP && cargo test --verbose