[package]
name = "rust_lsp"
version = "0.2.0"
authors = ["Bruno Medeiros <bruno.do.medeiros@gmail.com>"]
build = "build.rs"


[build-dependencies]
serde_codegen = "0.8"

[dependencies]
serde = "0.8"
serde_json = "0.8"

[lib]
name = "rust_lsp"
path = "src/lib.rs"

[[bin]]
name = "rust_lsp_app"
path = "src/main_lsp.rs"
test = false
