[package]
name = "rust_lsp"
version = "0.2.0"
authors = ["Bruno Medeiros <bruno.do.medeiros@gmail.com>"]
build = "build.rs"


[build-dependencies]
serde_codegen = "0.8"

[dependencies]
melnorme_util = { path = "lib/melnorme_util" }
melnorme_json_rpc = { path = "lib/melnorme_json_rpc" }
serde = "0.8"
serde_json = "0.8"

[lib]
name = "rust_lsp"
path = "src/lib.rs"

[[bin]]
name = "dummy_lsp"
path = "src/dummy_lsp.rs"
test = false

[features]
default = []
gen_sources = []